refactor/#34 notification failure handling
jvnlee/catch-dining pull request #35
Opened 2024-05-09 18:47 UTC by jvnlee

2024-05-11 02:47 UTC, Cyma-s requested changes
안녕하세요 현준님! 재시도가 가능하도록 코드를 변경해주셨네요.
몇 가지 부분에 대해 리뷰 남겼으니, 시간 되실 때 반영해주세요! 리뷰에 대해 질문이 있으시면 코멘트로 남겨주세요 🙂

2024-05-11 02:47 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/notification/service/NotificationRequestService.java
> +                    .build();
notification 은 언제나 동일한 내용이기 때문에 for 문 외부에 있는 것이 좋을 것 같네요 :)

2024-05-11 02:47 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/notification/service/NotificationRequestService.java
> +        List<NotificationRequest> list = notificationRequestRepository
변수 이름을 좀 더 의미있게 지어볼까요?

2024-05-11 02:47 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/notification/service/FirebaseMessagingServiceTest.java
> +    @MockBean
`@Mock` 과 `@MockBean` 의 차이점은 무엇일까요?

2024-05-11 02:47 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/notification/service/NotificationRequestServiceTest.java
>  import static org.mockito.Mockito.*;
와일드 카드 import 는 사용하지 않는 것이 좋아요. [구글 자바 스타일 가이드](https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports)에서 명시하고 있습니다!

<img width="980" alt="image" src="https://github.com/jvnlee/catch-dining/assets/61370551/87b243c5-0b7a-4abd-b40c-425760912df9">

다음과 같이 모두 999 로 넣어주면 와일드 카드 import 가 자동으로 되지 않아요 😄

2024-05-11 02:47 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/notification/service/NotificationRequestServiceTest.java
> +    void notify_success() {
현재는 알림 발송 성공, 토큰이 없는 경우만 테스트를 하고 있네요! 대부분의 경우에는 성공과 예외처리 테스트만 작성해도 무방해요. 
다만 notify 는 catchdining 서비스에서 꽤나 중요한 역할을 하고 있어요. 정말 롤백이 되는지, 제대로 기능을 수행하는지 확실하게 확인해야 하는 기능입니다.
이를 확인하기 위해, PaymentService cancel 메서드에서 에러가 발생했을 때 notify가 제대로 롤백이 되는지도 테스트해보면 어떨까요? 😊

2024-05-11 02:47 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/notification/service/FirebaseMessagingService.java
> +            // maxAttempts = 3 (default)
default 값으로 설정하려면 주석은 지워도 좋을 것 같습니다~!

2024-05-11 02:47 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/notification/service/NotificationRequestService.java
> +            } catch (MessageSendingFailureException e) {
특정 예외만 처리해준 부분 아주 좋아요 👍

2024-05-12 03:01 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/notification/service/FirebaseMessagingServiceTest.java
> +    @MockBean
`@Mock`은 스프링에 종속적이지 않은 일반적인 단위 테스트 환경에서 쓰입니다. 테스트 하고자 하는 대상이 가진 의존성에 해당 어노테이션을 붙여서 의존성 객체를 mock(가짜) 객체로 주입시킵니다. mock 객체는 테스트 코드 내부에서 stubbing 과정을 통해 동작 방식을 인위적으로 제어(리턴값 고정하거나, 예외를 유도하는 등)할 수 있기 때문에 이를 통해 실제 테스트 대상의 동작 방식을 살펴보는 데에 더 집중할 수 있습니다.

`@MockBean`도 `@Mock`처럼 의존성 객체를 mock 객체로 주입받도록 한다는 점과 stubbing을 목적으로 한다는 점은 유사하지만, `@SpringBootTest`라는 스프링에 의존하는 통합 테스트 환경에서 사용한다는 차이점이 있습니다. `@SpringBootTest`는 스프링 컨테이너를 기반으로 움직이기 때문에 Bean을 등록하고 사용할 수 있는데, 이 때 테스트하고자 하는 모듈이 주입받을 의존성 Bean에 `@MockBean`을 붙이면 가짜 Bean 객체를 주입시켜주고, stubbing을 통해 행동을 제어할 수 있습니다.

2024-05-12 03:12 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/notification/service/NotificationRequestServiceTest.java
>  import static org.mockito.Mockito.*;
찾아보니 와일드 카드 import를 사용하게 되면 불필요한 요소들까지 모두 함께 import 하게 되어 어떤 모듈을 사용하고자 했는지 코드의 명확성이 떨어진다는 점을 알 수 있었습니다. 그래서 Google을 비롯한 대부분의 개발 컨벤션에서 지양하고 있네요. 짚어주신 설정 반영했습니다!

2024-05-12 03:14 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/notification/service/FirebaseMessagingServiceTest.java
> +    @MockBean
너무 깔끔하게 정리해주셨네요 👍👍👍 훌륭합니다!

2024-05-14 04:26 UTC, merged