Feature/#41 restaurant api sorted search
jvnlee/catch-dining pull request #42
Opened 2024-05-27 15:45 UTC by jvnlee

## 구현 내용

### 정렬된 Restaurant 조회 쿼리 구현

`Restaurant` 조회 시 `Review` 테이블과 JOIN 시켜 동적으로 연산하는 값을 기준으로 정렬하는 메서드 구현

- `findPageByKeywordOrderByRating()`: `Restaurant`마다 가진 `Review`의 `tasteRating`, `moodRating`, `serviceRating` 값의 평균을 기준으로 내림차순 정렬한 `Restaurant` 페이지 반환

- `findPageByKeywordOrderByReviewCount()`: `Restaurant`가 가진 `Review`의 총 개수를 기준으로 내림차순 정렬한 `Restaurant` 페이지 반환

&nbsp;

### 쿼리 최적화

WIP

&nbsp;

### DTO 분리

기존에는 Repository &#8596; Service &#8596; Controller 계층 간 통신에 공통적으로 `RestaurantSearchDto`를 사용함.

계층 간 결합도, 특히 Data Access Layer와 Presentation Layer 간의 결합도를 낮추기 위해 DTO를 분리함

- `RestaurantSearchRequestDto`: Controller &#8594; Service (HTTP 요청에서 추출한 데이터 전달)

- `RestaurantSearchResultDto`: Repository &#8594; Service (DB에서 반환한 데이터 전달)

- `RestaurantSearchResponseDto`: Service &#8594; Controller (HTTP 응답으로 내보낼 데이터 전달)

2024-05-31 04:59 UTC, Cyma-s requested changes
안녕하세요 현준님 😄 쿼리 최적화 열심히 진행해주셨네요 👍🏻 꼼꼼하게 테스트해주신 부분도 너무 좋았습니다.
이번 리뷰는 코드의 의도에 대해 궁금한 부분이 많아서, 질문 위주로 남겼습니다. 시간 되실 때 리뷰 반영해주세요~!

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/common/advice/ControllerAdvice.java
> +    @ResponseStatus(BAD_REQUEST)
클래스에 정의되어 있는 상수 같은 경우는 static import 를 하지 않는 것이 좋을 수도 있습니다.
static import 를 하게 되면 해당 상수가 서비스에서 만들어진 상수인지, 기존에 존재하는 클래스의 상수인지 명확하게 알 수 없어져 코드를 읽는 개발자가 import 문을 읽어봐야 하는 일이 일어날 수 있어서 그렇습니다 :)

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/common/advice/ControllerAdvice.java
> +
만약 서버에서 handle 하지 못하는 예외가 발생한다면, 어떤 상태 코드로 처리해야 할까요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantController.java
> +    public Response<Page<RestaurantSearchResponseDto>> search(@RequestParam String keyword,
Page 객체를 응답으로 반환하는 이유는 무엇인가요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantController.java
> +                                                            Pageable pageable) {
Pageable 을 파라미터로 입력 받는 이유가 있을까요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantController.java
> +                .search(new RestaurantSearchRequestDto(keyword, sortBy, pageable));
파라미터들을 dto 로 감싸서 넘겨주셨네요. 이런 방법은 어떤 이점을 가지고 있나요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/dto/RestaurantSearchRequestDto.java
>  @Data
`@Data` 어노테이션을 쓴 이유가 무엇인가요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/dto/RestaurantSearchResponseDto.java
> +    private Address address;
응답 타입으로 Enum 을 넘긴다면, 실제 응답에서는 어떤 값이 보일까요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/dto/RestaurantSearchResponseDto.java
> +        this.reviewCount = r.getReviewCount();
이미 만들어져 있는 `@AllArgsConstructor` 를 사용하면 좋을 것 같네요!

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantRepository.java
> +            "where r.name like concat('%', :keyword, '%') " +
like 쿼리로 조회하는 로직을 넣어주셨네요 🤔
해당 쿼리는 mysql 에서 어떻게 처리되는지 알아보시면 좋을 것 같습니다 :) 알아보시고 댓글로 남겨주세요!

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantRepository.java
> +            "select r.id as id, r.name as name, r.address as address, round((avg(rv.tasteRating) + avg(rv.moodRating) + avg(rv.serviceRating)) / 3, 2) as rating, count(rv.id) as reviewCount " +
round 를 쿼리에서 처리하는 것과 애플리케이션에서 처리하는 것 중 어떤 것이 더 성능이 좋나요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +            if (sortBy.equals("rating")) {
sortBy 도 Enum 으로 관리할 수 있지 않을까요?

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +        if (sortBy == null) {
`@RequestParam` 에는 default 값을 정할 수 있는 속성도 있답니다!

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +        }
조회 결과가 없을 때 예외가 발생하는 것은 사용자 입장에서 예상치 못한 에러일 것 같네요 🤔

2024-05-31 04:59 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +
불필요한 공백은 지워주세요!

2024-05-31 04:59 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantControllerTest.java
>          );
DTO 분리해주신 부분 좋습니다 👍👍👍

2024-05-31 04:59 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantControllerTest.java
> +        PageImpl<RestaurantSearchResponseDto> page = new PageImpl<>(content);
`Page` 를 그대로 리턴하게 되면 테스트를 할 때마다 이렇게 Impl 이 있어야 하겠죠?

2024-05-31 04:59 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantControllerTest.java
> +                .andExpect(jsonPath("$.data.content[0].reviewCount").value(1000));
검증 로직이 조금 부족한 것 같아요. 데이터가 얼마나 들어 있고, 제대로 정렬되어 있는지 확인하는 로직이 있다면 더 좋을 것 같습니다!

2024-05-31 04:59 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantServiceTest.java
> +    class RestaurantSearchResultDtoImpl implements RestaurantSearchResultDto {
Dto Impl 이 있네요?! 서비스 테스트는 어떤 것을 테스트해야 한다고 생각하시나요?

2024-05-31 04:59 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantServiceTest.java
> +                .isEqualTo(3);
assert 문을 여러 개 두면, 위에서 예외가 발생했을 때 아래 구문은 실행되지 않는다는 문제점이 있어요.
assertAll 로 assert 문을 묶어주면, 위에서 예외가 발생하더라도 전체 assert 문이 실행됩니다!

2024-05-31 07:51 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/common/advice/ControllerAdvice.java
> +    @ResponseStatus(BAD_REQUEST)
그럴 수 있겠네요... 항상 동료 개발자가 함께 읽는 코드라고 생각하고 작성해보겠습니다.

2024-05-31 07:53 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/common/advice/ControllerAdvice.java
> +
> 만약 서버에서 handle 하지 못하는 예외가 발생한다면, 어떤 상태 코드로 처리해야 할까요?

500번대 상태 코드로 처리할 것 같습니다. 혹시 이 부분에도 서버에서 handle 하지 못할 우려가 있는 걸까요?

2024-05-31 07:56 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantController.java
> +    public Response<Page<RestaurantSearchResponseDto>> search(@RequestParam String keyword,
Page 객체 안에는 페이징에 관련된 유용한 데이터(페이지 번호, 페이지 사이즈, 총 페이지 수 등...)가 응집되어 있어서 클라이언트 개발자가 필요에 따라 사용할 수 있도록 하려는 취지로 반환해주었습니다.

2024-05-31 07:59 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantController.java
> +                                                            Pageable pageable) {
컨트롤러 메서드의 파라미터로 Pageable 타입을 넣으면, URL 쿼리 파라미터에 `page`, `size` 등 페이징에 관련되어 요청할 수 있는 항목들을 넣을 수 있어서 다이나믹한 요청이 가능하다고 보았습니다. 요청에 따라 해당 옵션들을 다르게 사용할 수도 있고, 사용하지 않을 수도 있는데 Pageable 파라미터가 그러한 다양한 상황의 요청들을 유연하게 커버해주었습니다.

2024-05-31 08:01 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantController.java
> +                .search(new RestaurantSearchRequestDto(keyword, sortBy, pageable));
계층 간 데이터 통신 시, 보내려는 데이터를 외부에서 한번에 보여지지 않게 캡슐화할 수 있습니다. 또한 보내려는 항목이 많을 때, 파라미터로 일일이 넣어주지 않고 DTO 객체를 넘겨줌으로써 코드가 단순해지고 보기 편해진다는 장점도 있습니다.

2024-05-31 08:03 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantControllerTest.java
> +        PageImpl<RestaurantSearchResponseDto> page = new PageImpl<>(content);
실제 응답 상황에서는 내부에서 자동적으로 Impl 객체를 만들어서 반환해주는 것으로 알고 있습니다. 테스트 할때에만 이렇게 수동으로 생성해주면 되어서 크게 불편함이 없더라도 구조적인 변경을 적용해야 할까요?

2024-05-31 08:04 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantControllerTest.java
> +                .andExpect(jsonPath("$.data.content[0].reviewCount").value(1000));
반영해보겠습니다!

2024-05-31 08:13 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantServiceTest.java
> +                .isEqualTo(3);
몰랐는데 그런 맹점이 있었네요 😮 반영해보겠습니다!

2024-05-31 08:15 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/dto/RestaurantSearchRequestDto.java
>  @Data
어차피 DTO에는 초기화 단계에서만 데이터 주입이 이루어지고, 나중에 데이터가 변경되는 일은 없으니 `@Getter`로 수정하는 것이 낫겠네요. 지적 감사합니다

2024-05-31 08:17 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/dto/RestaurantSearchResponseDto.java
> +    private Address address;
`Address`는 embedded 타입입니다. 실제 응답을 확인해보니 `Address` 안에 모아놓았던 세부 문자열 항목들이 다시 분리되어 열거되어 있었습니다.

2024-05-31 08:19 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/dto/RestaurantSearchResponseDto.java
> +        this.reviewCount = r.getReviewCount();
`@AllArgsConstructor` 방식 외에도 `RestaurantSearchResultDto`에서 값을 뽑아서 해당 DTO로 매핑시키는 형태의 생성자가 필요해서 생성했습니다.

2024-05-31 08:22 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +            if (sortBy.equals("rating")) {
Enum으로 전환해보겠습니다!

2024-05-31 08:23 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +        if (sortBy == null) {
반영해보겠습니다!

2024-05-31 08:24 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +        }
이 부분은 지난번에 언급해주셨던 것을 기억합니다. 200 상태코드로 비어있는 컬렉션을 반환하는게 더 논리적일 것 같습니다. 반영해보겠습니다!

2024-05-31 09:58 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +        if (sortBy == null) {
sorBy의 기본값은 따로 정해져 있지 않은데 어떤 의도로 말씀해주셨는지 알 수 있을까요?

2024-05-31 10:07 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantRepository.java
> +            "select r.id as id, r.name as name, r.address as address, round((avg(rv.tasteRating) + avg(rv.moodRating) + avg(rv.serviceRating)) / 3, 2) as rating, count(rv.id) as reviewCount " +
일단 둘다 시도해보기 전에 예상을 해보자면, 큰 차이는 없을 것 같습니다.

round의 실행 횟수는 현재 Restaurant의 개수와 동일하게 1000회(집계 완료된 평균값을 커팅하는 작업이므로) 일 것이고, 데이터베이스 엔진에게 1000회 정도의 연산으로 인한 성능 차이는 미약할 것 같습니다. 실제로 시도해보고 나서 추가 댓글 달아놓겠습니다.

2024-05-31 10:30 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/common/advice/ControllerAdvice.java
> +
지금은 명시적으로 적어준 Exception 들만 ControllerAdvice 에서 처리되고 있기 때문에, 그 외의 예외 (NoSuchElementException 등등...) 들은 예외 메시지가 그대로 응답으로 전달될 거에요. 이를 위해서는 그 이외의 일반 Exception 은 어떻게 처리할 것인지 명시적으로 적어주는 게 좋겠죠!

2024-05-31 10:31 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/dto/RestaurantSearchResponseDto.java
> +        this.reviewCount = r.getReviewCount();
남긴 리뷰의 뜻은 이런 식으로 바꿔보면 좋을 것 같다는 뜻이었습니다 :)
```suggestion
        this(r.getId(), r.getName(), r.getAddress(), r.getRating(), r.getReviewCount());
```

2024-05-31 10:35 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantService.java
> +        if (sortBy == null) {
`@RequestParam` 에서 default 값을 정하게 되면 굳이 sortBy 가 null 인 경우에 대한 처리를 하지 않아도 되지 않을까요?

2024-05-31 10:36 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantServiceTest.java
> +    class RestaurantSearchResultDtoImpl implements RestaurantSearchResultDto {
테스트를 하는 방식에는 여러가지가 있는데, 현재 서비스는 JPA 에 크게 의존을 하고 있어요. 그렇다면 굳이 JPA 와 서비스의 의존성을 분리하려고 하지 않고, 통합으로 테스트를 진행해도 되지 않을까요? 만약 그렇게 된다면 JPA 를 모킹할 필요 없이, 실제 동작을 확인해보면 되니까요!

2024-06-02 11:13 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/controller/RestaurantControllerTest.java
> +        PageImpl<RestaurantSearchResponseDto> page = new PageImpl<>(content);
Impl 을 만드는 것이 불편하지 않다면 Page 같은 경우는 그대로 사용해도 될 것 같네요!

2024-06-02 11:16 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantRepository.java
> +            "where r.name like concat('%', :keyword, '%') " +
mysql 의 like 쿼리의 경우, name% 형태로 된 like 쿼리만 인덱스를 적용할 수 있습니다. 인덱스는 시작 값으로 정렬이 되기 때문에, %name 형태나, %name% 형태는 테이블을 모두 찾아야 찾을 수 있겠죠!

이를 위해 검색 엔진을 사용하거나, FULL-TEXT scan 을 사용하기도 합니다!

2024-06-02 13:42 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantServiceTest.java
> +    class RestaurantSearchResultDtoImpl implements RestaurantSearchResultDto {
@Cyma-s 이해했습니다! 그런데 다른 도메인의 서비스 코드처럼 순수한 단위 테스트를 하고 싶어서 우선은 이렇게 두려고 합니다.

2024-06-02 13:50 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantServiceTest.java
> +                .isEqualTo(3);
해당 기능은 JUnit의 기능이라서 현재 제가 사용하고 있는 AssertJ에는 없는 것 같습니다. 추후에 JUnit 사용 시 적용해보겠습니다!

2024-06-02 14:05 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantRepository.java
> +            "where r.name like concat('%', :keyword, '%') " +
@Cyma-s 말씀해주신대로 찾아보니, Elastic Search 같은 외부 검색 엔진 툴을 사용하면 대량 데이터셋에서 패턴 매칭을 할 때 full table scan 보다 나은 성능을 기대할 수 있다고 하네요. Elastic Search는 Inverted Index를 사용해서 Full Text Scan을 진행하여 빠른 검색이 가능하다는 사실을 알게 되었습니다.

&nbsp;

Elastic Search 적용은 추후에 별도의 Issue로 만들어서 진행해보도록 하겠습니다.

2024-06-03 12:53 UTC, merged