feature/#43 cqrs application
jvnlee/catch-dining pull request #44
Opened 2024-06-03 23:07 UTC by jvnlee

## 구현 내용

`DataSource`를 하나만 가지고 있던 기존 구조에서, READ용과 WRITE용 2개를 가지도록 변경하고 필요에 따라 Routing 하는 기능을 구현함. 

&nbsp;

## CQRS 패턴 도입

CQRS 패턴 도입이라고 표현했으나, 엄밀하게는 아님. CQRS 패턴은 READ용 DB로만 READ를 수행하고, WRITE용 DB로만 CREATE/UPDATE/DELETE를 진행하지만, 현재 프로젝트에서는 도입 취지 상, 집계 데이터가 포함되는 특정 조회 API의 성능 향상에 우선 초점을 두고 있음. 

따라서 해당 조회 API의 경우에만 READ DB로부터 조회를 수행하고, 나머지 일반 조회 API의 경우는 우선 WRITE DB에서 조회를 수행하도록 함.

## docker-compose.yml

- yml 파일을 dev와 prod 프로필별로 구분하여 빌드 방식과 환경 변수 세팅을 다르게 진행

- mysql이라는 이름의 단일 데이터베이스 컨테이너를 사용하던 환경에서, read-db와 write-db 2개의 데이터베이스 컨테이너를 사용하도록 변경

- health check condition을 추가하여 2개의 DB 컨테이너가 모두 정상적으로 실행된 경우에만 app 컨테이너를 실행하도록 함

    > app 컨테이너 시작 시, Spring Boot가 DB 초기화 전에 Application Context를 초기화하여 실패하는 문제 방지

- Git에 공개하지 않은 init.sql 파일 실행하는 옵션 추가

    > init.sql: DB 사용자 권한 설정과 DDL 실행

&nbsp;

## DataSourceRouter

- `AbstractRoutingDataSource`를 구현하여 현재 `DataSourceType`을 보고 적절한 `DataSource`로 찾아가도록 안내하는 역할

    > `ThreadLocal` 변수로 현재 `DataSourceType`을 보관

- `determineCurrentLookupKey()`: `currentDataSource` 필드로부터 현재 타겟으로 하는 `DataSourceType`을 읽어와 로그로 남기고 반환

&nbsp;

## DataSourceConfig

- `writeDataSource()` & `readDataSource()`: 각각 쓰기 데이터베이스와 읽기 데이터베이스를 위한 `DataSource` Bean 초기화

- `dataSourceRouter()`: `DataSourceRouter`를 Bean을 만들고, 2개의 `DataSource`를 Map에 넣어 타겟으로 지정함.

- `lazyDataSource()`: `DataSourceRouter`를 프록시로 감싸서 커넥션 획득을 지연시키는 `LazyConnectionDataSourceProxy` Bean 초기화

&nbsp;

## EntityManagerFactoryConfig

(dev와 prod 프로필용으로 구분되어 있음)

- `~entityManagerFactory()`: `LazyConnectionDataSourceProxy`를 DataSource로 사용하는 커스텀 `EntityManagerFactory`를 생성

&nbsp;

## TransactionManagerConfig

- `transactionManager()`: 커스텀 `EntityManagerFactory`를 적용할 커스텀 `JpaTransactionManager`를 생성

&nbsp;

## ReadOnly 어노테이션

기존 Service 조회 메서드들에 `@Transactional(readOnly = true)`가 붙어있는 것과 별개로, `@ReadOnly`라는 커스텀 어노테이션이 붙어있어야만 READ_ONLY 데이터베이스로 라우팅됨.

&nbsp;

## DataSourceRoutingAspect

Spring AOP를 이용하여 `@ReadOnly` 어노테이션이 붙은 메서드가 호출될 때, `DataSourceRouter`가 타겟을 `READ_ONLY`로 변경하도록 함.

&nbsp;

## DataSourceRouterCleanerInterceptor

`DataSourceRouter`가 가진 `ThreadLocal` 변수를 기본값인 `WRITE_ONLY`로 초기화시킴

> 초기화 하지 않는 경우 잔존 값으로 인해 발생하는 버그를 방지

2024-06-05 05:05 UTC, Cyma-s requested changes
안녕하세요 현준님! 반영하시느라 고생 많으셨습니다 👍 코드 관련한 코멘트는 없고, 궁금한 부분 한 가지 있어 리뷰 남겼습니다! 시간 되실 때 확인해주세요~

2024-06-05 05:05 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/common/util/DataSourceRouter.java
> +    }
reset 메서드를 따로 만들어두지 않으면 데이터소스가 남아있는 문제가 있었나요?

2024-06-05 05:05 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/user/dto/UserSearchResponseDto.java
> +@NoArgsConstructor
NoArgsConstructor 어노테이션을 추가해주신 이유가 있을까요?

2024-06-11 18:06 UTC, jvnlee commented on docker-compose.dev.yml
> +    healthcheck:
넵 healthcheck 옵션을 넣으니 DB 초기화를 기다렸다가 APP을 실행할 수 있어서 간혹 발생했던 Application Context의 로드 실패 문제를 겪지 않게 되었습니다!

2024-06-11 18:07 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/common/config/TransactionManagerConfig.java
> +public class TransactionManagerConfig {
Configuration을 되도록 목적별로 분리하는 것이 유지보수성이 좋다고 생각해서 분리했습니다!

2024-06-11 18:09 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/common/util/DataSourceRouter.java
> +    }
DataSource는 Application Context와 생명주기를 같이하기 때문에 잔존 값이 충분히 남아있을 수 있다고 생각했습니다. 실제로 발생하지는 않았으나 혹시나 생길 수 있는 문제를 방지하기 위해 넣었습니다!

2024-06-11 18:10 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/user/dto/UserSearchResponseDto.java
> +@NoArgsConstructor
불필요한 어노테이션인 것 같네요 빼도록 하겠습니다!

2024-06-15 13:36 UTC, Cyma-s requested changes
안녕하세요 현준님! 수정 사항 반영하시느라 고생 많으셨습니다 👏
새롭게 수정해주신 부분에서 궁금한 부분이 있어 리뷰 남겨보았습니다. 혹시 이해가 잘 안 되시는 부분이 있으면 알려주세요!

2024-06-15 13:36 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantReviewStatRepository.java
> +    Page<RestaurantSearchResultDto> findPageByKeywordSortByAvgRating(String keyword, Pageable pageable);
여기서도 RestaurantSearchResultDto 를 쓰신 이유가 있을까요?

2024-06-15 13:36 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantReviewStatService.java
> +        }
하나의 변수를 두고 if 마다 값을 다르게 하는 것보다 각 if 문에서 return 을 바로 해버리는 게 좋습니다!

2024-06-15 13:36 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/review/event/ReviewCreatedEvent.java
> +    public ReviewCreatedEvent(Long restaurantId, Review rv) {
파라미터가 `Review` 일 경우와 `tasteRating`, `moodRating`, `serviceRating` 각각을 입력 받는 경우 중에 어떤 것이 더 나을까요?

2024-06-15 13:36 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/user/model/User.java
> +    @OneToMany(mappedBy = "user", cascade = ALL, orphanRemoval = true)
여기에 해당 속성들을 모두 붙여주신 이유가 무엇일까요?

2024-06-15 13:36 UTC, Cyma-s commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantReviewStatServiceTest.java
> +        when(repository.findById(restaurantId)).thenThrow(RestaurantNotFoundException.class);
실제로 레포지토리에서 CustomException 을 리턴하나요?

2024-06-17 00:11 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/common/util/QueryInspector.java
> +    private ThreadLocal<Integer> executionCount = ThreadLocal.withInitial(() -> 0);
Restaurant과 관련된 이벤트들이 비동기 처리되다보니 HTTP 요청 처리가 끝난 이후에도 SQL이 실행되어 QueryInspector가 호출되는 문제가 있었습니다. 따라서 해당 Bean을 Request Scope에서 Singleton Scope로 변경할 수 밖에 없었고, executionCount 변수 또한 thread-safe 하도록 ThreadLocal 타입으로 변경했습니다.

[관련 커밋](https://github.com/jvnlee/catch-dining/pull/44/commits/18faf7b27e4826e4919e1db446bf4970982559f4)

2024-06-17 00:25 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/event/RestaurantCreatedEvent.java
> +    private Restaurant restaurant;
영속성 컨텍스트는 트랜잭션과 life cycle을 함께 합니다. 즉, 트랜잭션 시작부터 종료까지의 범위에만 유효합니다. 그런데 이벤트는 트랜잭션 종료 이후에도 비동기적으로 처리될 수 있기 때문에 이벤트 처리 시점에는 영속성 컨텍스트가 유효하지 않을 수 있습니다. 따라서 이벤트 처리 시점에 참조되는 엔티티는 영속성 컨텍스트의 관리를 받지 않는 detached 상태일 것입니다.

답변을 적고 보니 이벤트 객체에서 엔티티를 직접 참조하기 보다는 DTO를 참조하는 것이  더 안전한 코드라는 생각이 듭니다. DTO는 영속성 컨텍스트의 관리를 받지 않기 때문입니다.

2024-06-17 00:25 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/event/RestaurantDeletedEvent.java
> +public class RestaurantDeletedEvent {
Restaurant 삭제 시 발행되는 이벤트입니다. Review에는 삭제 기능이 없습니다.

2024-06-17 00:31 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/model/Restaurant.java
> +    @OneToMany(mappedBy = "restaurant", cascade = ALL, orphanRemoval = true)
현재 엔티티의 영속 상태를 연관 관계에 있는 엔티티에게 전이시키는 옵션입니다. PERSIST, MERGE, REMOVE, REFRESH, DETACH, ALL 옵션이 있으며 각 이름의 영속 상태를 연관 엔티티에 전이시킬 수 있는 옵션입니다. ALL의 경우는 모든 상태를 다 전이시킬 수 있도록 하는 옵션입니다.

2024-06-17 00:36 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantReviewStatRepository.java
> +    Page<RestaurantSearchResultDto> findPageByKeywordSortByAvgRating(String keyword, Pageable pageable);
해당 DTO는 Repository와 Service 레이어 간 통신에 사용되는 DTO입니다. 저번에 DTO 분리에 대해 지적해주셔서 Service와 Controller 레이어 간 통신에 사용하는 RestaurantSearchResponseDto와 구분한 것입니다. 혹시 여기에 무슨 문제가 있을까요?

2024-06-17 00:38 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/review/event/ReviewCreatedEvent.java
> +    public ReviewCreatedEvent(Long restaurantId, Review rv) {
이 [코멘트](https://github.com/jvnlee/catch-dining/pull/44#discussion_r1639325358)에서 답변드린것과 동일하게 후자가 더 나은 구조라고 생각합니다.

2024-06-17 00:41 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/user/model/User.java
> +    @OneToMany(mappedBy = "user", cascade = ALL, orphanRemoval = true)
의도는 해당 필드의 엔티티들이 User의 영속상태를 따라가야하며, User가 삭제되면 존재 이유가 없어지므로 함께 삭제되어야한다는 것이었습니다. 비즈니스 정책에 따라 다르겠지만 지금 다시 보니 Review와 Reservation 같은 경우는 보존하는 것이 맞아서 해당 옵션을 조정할 필요가 있는 것 같습니다.

2024-06-17 00:44 UTC, jvnlee commented on src/test/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantReviewStatServiceTest.java
> +        when(repository.findById(restaurantId)).thenThrow(RestaurantNotFoundException.class);
잘못된 코드입니다. thenReturn으로 Optional.empty()를 반환하는 것이 맞습니다.

2024-06-19 05:21 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/service/RestaurantReviewStatService.java
> +        }
page를 받아온 후 page 원소들을 RestaurantSearchResponseDto로 mapping 하는 공통 로직이 들어가기 때문에 return 문을 뒤로 뺐습니다.

2024-06-21 14:40 UTC, Cyma-s commented on src/main/java/com/jvnlee/catchdining/domain/review/event/ReviewCreatedEvent.java
> +    public ReviewCreatedEvent(Long restaurantId, Review rv) {
넵 이런 이벤트 구조에서는 도메인 객체를 그대로 전달하는 것보다 필요한 정보를 분리해서 담아보내는 것이 일반적입니다!

2024-06-21 21:49 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/restaurant/repository/RestaurantReviewStatRepository.java
> +    Page<RestaurantSearchResultDto> findPageByKeywordSortByAvgRating(String keyword, Pageable pageable);
어쩐지 현 구조대로라면 DTO가 너무 많아지지 않을까 했는데, 일반적인 practice는 여기서 DTO를 안쓰는거였네요 😅

2024-06-21 21:50 UTC, jvnlee commented on src/main/java/com/jvnlee/catchdining/domain/review/event/ReviewCreatedEvent.java
> +    public ReviewCreatedEvent(Long restaurantId, Review rv) {
이 부분 변경해보도록 하겠습니다!

2024-06-21 23:46 UTC, merged